server:
  port: 8000
spring:
  config:
    import: optional:configserver:http//localhost:8080
  datasource:
    url: jdbc:postgresql://localhost:5432/udemy_learning
    username: postgres
    password: 12345
  application:
    name: functions-service

math-service:
  endpoints:
    user-service: localhost:8100

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
