server:
  port: 8100
spring:
  config:
    import: optional:configserver:http//localhost:8080
  datasource:
    url: jdbc:postgresql://localhost:5432/udemy_learning
    username: postgres
    password: 12345
  application:
    name: user-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      retry-api-1:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
      retry-api-2:
        max-attempts: 4
        wait-duration: 2s
  ratelimiter:
    instances:
      my-rate-limiter:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      my-bulkhead:
        max-concurrent-calls: 2
